spring:
  application:
    name: Medicine-Project

  datasource:
    url: jdbc:postgresql://localhost:5432/Medicine_Project
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
